### ISSUE TITLE
[An issue] no releases page

### ISSUE THREAD

**Issue by dxcvvxd** [ngelsi/tsuki-tag-native#2]
how do i install it if there's no releases tab
![image](https://user-images.githubusercontent.com/77129815/236634621-a5f786d7-1847-4a6f-b00e-426e25104176.png)
![image](https://user-images.githubusercontent.com/77129815/236634643-77b38c04-f510-4ce4-8e1d-2328b426d230.png)

**Comment by ngelsi** [comment]
Hi there!

The Releases section can be found on the right panel. If you click the Releases text, the latest release will be on top.

![image](https://user-images.githubusercontent.com/12906850/236637463-75451bf3-ae37-490f-aa81-3be03dfa358e.png)

You can just download the zip file for your operating system there. If you are on Linux, you can also use Flathub to install the Flatpak version and get automatic updates as well.

[https://flathub.org/apps/eu.ngdevelopment.tsukitag](https://flathub.org/apps/eu.ngdevelopment.tsukitag)

**Comment by dxcvvxd** [comment]
oh, sorry, i had the refined github extension installed and it kind of changed the placement of the releases tab. whoops.
